### ISSUE TITLE
No bottom bar on fvwm95

### ISSUE THREAD

**Issue by longboarder241** [mintsuki/fvwm95#5]
So after I built the window manager and loaded it into my lxdm config I decided to boot it yet doing so only showed a blue background and my left and right click menus but no bottom bar.  Any help in getting it to work?  I built it on void linux

**Comment by misterspock1** [comment]
Yeah it appears that Fvwmtaskbar while present in the build directory, fails to build.

**Comment by Mintsuki** [comment]
WIP at the moment. Mentioned PR closed so that it can be split into multiple, smaller PRs.
