### ISSUE TITLE
configure doesn't find an install-sh script Debian 10

### ISSUE THREAD

**Issue by glymph** [mintsuki/fvwm95#9]
I'm not sure why, but the configure script didn't originally find an install-sh after the sequence of commands in the README were executed on my x86_64 Debian 10 machine. The commands below succeeded in creating it, and configure managed to complete, and I could run 'make' to compile:

libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure

Found on https://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux

**Comment by Mintsuki** [comment]
What about `libtoolize -cfvi && autoreconf -fvi` instead?
